### ISSUE TITLE
Domanda su obbligatorietà verifica DRL / possibilità di posticipare il primo download

### ISSUE THREAD

**Issue by DevTrevi** [ministero-salute/it-dgc-documentation#14]
Buongiorno a tutti, 

attualmente in DgcReader quando viene richiesta la validazione di un greenpass, la libreria consente l'utilizzo di valori non aggiornati, avviando il download degli aggiornamenti di certificati, regole e blacklist in un task in background, fornendo quindi un risultato immediato all'utilizzatore e causando un leggero ritardo nell'utilizzo di valori aggiornati (in pratica, è come se si posticipasse per il  tempo necessario al download la scadenza di tali valori, dato che la richiesta di validazione avvierebbe il download, e solo la richiesta successiva potrebbe utilizzare effettivamente i valori aggiornati).

Se però tali valori fossero più vecchi di una soglia limite, definita come MaxFileAge, oppure se nessun valore fosse disponibile (download mai eseguito), allora verrebbe comunque atteso il completamento del download prima di fornire un risultato.

Questo comportamento non causa problemi con certificati e regole, che richiedono pochi secondi per il completamento del download, mentre l'aggiornamento della blacklist al primo download può richiedere anche alcuni minuti.

Mi viene chiesto di consentire di poter saltare l'attesa sul download della blacklist al primo utilizzo, avviando il download in background ma fornendo quindi un risultato senza che la DRL sia stata verificata.
Nella [Documentazione per la DGC Revocation List](https://github.com/ministero-salute/it-dgc-documentation/blob/master/DRL.md#panoramica) leggo:

_1. la verifica della DRL dovrebbe essere implementata come uno step opzionale del processo, in maniera tale che il suo stato possa essere guidato da un apposito configuration item propagato tramite la Piattaforma Nazionale;_
_2. il mancato aggiornamento della DRL implica una visione potenzialmente non corretta e non completa dell'insieme dei DGC prodotti dalla Piattaforma Nazionale, per tanto dovrebbero essere previsti dei controlli sullo stato di aggiornamento della DRL in grado di inibire la scansione dei DGC_

Mi chiedevo quindi se lo step di verifica della DRL potesse essere considerato "opzionale" o comunque non bloccante, in modo da poter posticipare il download e consentire una validazione quasi immediata al primo utilizzo. 
In questo caso, potrei aggiungere un parametro opt-in che consentirebbe questo comportamento, ma non sono certo che questo sia conforme al comportamento previsto

**Comment by rawmain** [comment]
Buongiorno @DevTrevi 

> Mi viene chiesto di consentire di poter saltare l'attesa sul download della blacklist al primo utilizzo, avviando il download in background ma fornendo quindi un risultato senza che la DRL sia stata verificata.
[...]
> In questo caso, potrei aggiungere un parametro opt-in che consentirebbe questo comportamento, ma non sono certo che questo sia conforme al comportamento previsto

Come hai già immaginato, la possibilità di una tale opzione anche in ambito d'uso produzione/release (_non solo debug/test_) non è infatti conforme a prescrizioni + istruzioni operative.

La validazione non deve essere consentita se - oltre a Validation Rules + KIDS - non sia stato completato correttamente anche DRL fetch/sync in 1st Run o dopo reset DB. Idem anche qualora sia rilevato diff/snapshot update in esecuzione scheduler/worker per controllo/aggiornamento periodico.

-----------------------

Per il resto, ho letto la [issue](https://github.com/DevTrevi/DgcReader/issues/55) da cui origina tale richiesta, che ti è stata sottoposta.

Vedo che il delay riscontrato con l'attuale release DgcReader & segnalato dall'utente con sua specifica impostazione app+librerie, seppur superiore ai 60s, è intorno ai 3 minuti.

Peraltro, avvenendo solo in caso di run con DB vuoto (_ergo, 1st run o reset_), non influenza cmq le performance delle successive operazioni.

Non vedo quindi motivazioni tecniche, onde consentire - anche in config produzione/release - un tale override di quanto disposto da prescrizioni + istruzioni operative.

Corretto invece - _come hai anche indicato all'utente nella issue_ - aggiungere alla libreria l'esposizione event di notifica del progresso fetch/sync DRL, onde consentire maggior evidenza di tale processo lato UI/applicazione con elementi grafici testuali (_stile quanto fa DGC-SDK per la whitelabel-app VerificaC19_).

**Comment by DevTrevi** [comment]
Grazie mille per il chiarimento @rawmain, a questo punto implementerò solo la notifica del progresso.

Per quanto riguarda il comportamento per i successivi aggiornamenti, pensi sia accettabile la strategia utilizzata, ovvero consentire l'utilizzo di valori "scaduti" mentre vengono scaricati i valori aggiornati?

**Comment by rawmain** [comment]
Ciao @DevTrevi 

> Grazie mille per il chiarimento

Prego ;).

> Per quanto riguarda il comportamento per i successivi aggiornamenti, pensi sia accettabile la strategia utilizzata, ovvero consentire l'utilizzo di valori "scaduti" mentre vengono scaricati i valori aggiornati?

In ambito produzione la validazione con DB locale non allineato, _cioè con entry DRL da versione anteriore a quella dell'ultimo snapshot disponibile online_, è ammessa solo finché il client non effettui il controllo online aggiornamenti (_automatico periodico con schedule <=24h o forzato manualmente da operatore_) & rilevi la disponibilità della nuova versione.

Pertanto, se il client rileva l'effettiva disponibilità di una nuova versione DRL online, deve essere cmq inibito l'avvio di acquisizione QR / stringa qrcodetext per validazione DGC/CRT, finché non risultino completati correttamente fetch DRL diff/snapshot & DB reconciliation.

**Comment by DevTrevi** [comment]
Capito, quindi in pratica il parametro 
``` csharp
/// <summary>
/// If true, allows to use the current values without waiting for the refresh task to complete.
/// Otherwise, if the list is expired, every rules valdation request will wait untill the refresh task completes.
/// </summary>
public bool UseAvailableValuesWhileRefreshing { get; set; } = true;
```
non dovrebbe essere consentito, oppure potrebbe essere consentito solo se la nuova versione viene rilevata a distanza inferiore di 24h dal precedente download (in questo caso è come se il client non fosse ancora venuto a conoscenza dell'aggiornamento)?

Mi rendo conto che è una forzatura delle specifiche, ma questa opzione consente di mantenere tempi di risposta molto rapidi e prevedibili, soprattutto in scenari server con richieste di validazione simultanee, causando tipicamente un ritardo nell'utilizzo di valori aggiornati di pochi secondi.

Anche i provider dei certificati di firma e delle regole utilizzano la stessa logica, anche per questi non dovrebbe essere consentita questa strategia a tuo avviso?

**Comment by rawmain** [comment]
Ciao @DevTrevi 

> `public bool UseAvailableValuesWhileRefreshing { get; set; } = true;`
>
> non dovrebbe essere consentito, oppure potrebbe essere consentito solo se la nuova versione viene rilevata a distanza inferiore di 24h dal precedente download (in questo caso è come se il client non fosse ancora venuto a conoscenza dell'aggiornamento)?

In virtù cmq delle condizioni per consentire esecuzione verifiche offline - _valide tanto per VerificaC19 quanto per SDK/Lib terze_ - le istruzioni operative possono solo limitarsi ad indicare di minimizzare il numero di validazioni effettuate con valori obsoleti di Rules / KIDs / DRL.

L'impostazione true/false di tale flag & le opzioni di pianificazione fetch/sync dipendono perciò da scenario/carico d'uso & grado (_desiderato/vincolato_) di minimizzazione, come hai anche indicato nelle [note specifiche di config per uso DgcReader in validazioni ITA](https://github.com/DevTrevi/DgcReader/blob/e89ea700e1f09b904f8af0c3ebb6e704b5a2337c/ItalianConfiguration.md).

In base a tale quadro ci può quindi stare - anche in ambito di verifiche manuali/handheld - un'impostazione meno rigida & disruptive per gestione/ottimizzazione flussi di acquisizione->validazione, come appunto l'impostazione del value true per tale flag. 

In tal caso suggerirei cmq di implementare anche esposizione/event di notifica per chunk `totalSizeInByte` > 5 MB, sempre nell'ottica di maggior evidenza dei processi DRL lato UI/applicazione, nonché per consentire possibilità di valutazione/intervento all'operatore in virtù di dismissable alert.

**Comment by DevTrevi** [comment]
Perfetto, come sempre ti ringrazio per l'aiuto, avevo il dubbio di dover eliminare del tutto questa opzione.
Esporrò degli eventi di notifica e eventualmente cambierò il default di questa opzione in modo che risulti opt-in, onde evitare ritardi negli aggiornamenti non desiderati 👍
